- app/chrony/README.md
- app/chrony/Template_App_chrony_active.xml
This is as simple as can be. I'll add more if we ever feel like it.
> Basic chrony daemon monitoring

- app/zabbix-agent/Template_App_Zabbix_Agent_active.xml
> Add online description that point back to repo

- update-app-doc.xsl
Some fixes and enhancements for the update-app-doc XSL
> update-app-doc enhancements

- app/chrony/README.md
- app/ntpd/README.md
- app/zabbix-agent/README.md
These changes where missing from #12 after it was merged. Until we setup something fancy to host the READMEs we'll have to run `make update` and commit it's results this with each PR.
> Run make update

- app/MD-RAID/README.md
- app/MD-RAID/Template_App_MD-RAID_active.xml
- app/MD-RAID/doc/README.UserParameters.md
- app/MD-RAID/doc/README.head.md
- app/MD-RAID/userparameters/rabe.md-raid.conf
Monitoring of Linux MD-RAID devices (aka Linux Software RAID).
> Feature - Linux MD-RAID

- app/Axia_ALSA_Soundcard_Driver_for_Livewire/README.md
- app/Axia_ALSA_Soundcard_Driver_for_Livewire/Template_App_Axia_ALSA_Soundcard_Driver_for_Livewire_active.xml
- app/Axia_ALSA_Soundcard_Driver_for_Livewire/doc/README.head.md
Monitoring of the AXIA - ALSA soundcard driver for Livewire (Axia IP Audio Driver for Linux).
> Feature - App Templates for AXIA - ALSA

- Makefile
- README.md
- os/FreeBSD/README.md
- os/Linux/README.md
This PR adds support for OS template documentation generation and adds a development section to the main README.
> Feature - OS templates

- ipmi/Supermicro_X7DWU/README.md
- ipmi/Supermicro_X7DWU/Template_IPMI_Supermicro_X7DWU.xml
- ipmi/Supermicro_X7DWU/doc/README.head.md
Monitoring of Supermicro motherboard [X7DWU](http://www.supermicro.com/products/motherboard/Xeon1333/5400/X7DWU.cfm) IPMI sensors.
This PR depends on #35 and #33.
> Feature - IPMI Supermicro X7DWU

- ipmi/Supermicro_SSG-6048R-E1CR24N/README.md
- ipmi/Supermicro_SSG-6048R-E1CR24N/Template_IPMI_Supermicro_SSG-6048R-E1CR24N.xml
- ipmi/Supermicro_SSG-6048R-E1CR24N/doc/README.head.md
Monitoring of Supermicro SuperStorage Server [6048R-E1CR24N](https://www.supermicro.com/products/system/4u/6048/ssg-6048r-e1cr24n.cfm) IPMI sensors.
This PR depends on #32 and #34.
> Feature - IPMI Supermicro 6048R-E1CR24N

- ipmi/Drive_Slot_Sensors/README.md
- ipmi/Drive_Slot_Sensors/Template_IPMI_Drive_Slot_Sensors.xml
- ipmi/Drive_Slot_Sensors/doc/README.head.md
Monitoring of auto-discovered IPMI drive slot sensors (sensor type code 0Dh).
> Feature - IPMI drive slot sensors

- app/Darkice/README.md
- app/Darkice/Template_App_Darkice_active.xml
- app/Darkice/doc/README.head.md
Monitoring of [Darkice](http://www.darkice.org/).
> Feature - App Darkice

- app/auditd/README.md
- app/auditd/Template_App_auditd_active.xml
- app/auditd/doc/README.head.md
Monitoring of [auditd](https://people.redhat.com/sgrubb/audit/).
> Feature - App auditd

- app/GlusterFS_Client/README.md
- app/GlusterFS_Client/Template_App_GlusterFS_Client_active.xml
- app/GlusterFS_Client/doc/README.head.md
Monitoring of [GlusterFS Client(s)](https://www.gluster.org/).
> Feature - App GlusterFS client

- app/GlusterFS_Server/README.md
- app/GlusterFS_Server/Template_App_GlusterFS_Server_active.xml
- app/GlusterFS_Server/doc/README.head.md
Application template for the [GlusterFS](https://www.gluster.org/) server `glusterfsd`.
> Feature - App GlusterFS server

- README.md
Add the required git commands and include the generation of a minimal documentation to ease and streamline the development of Zabbix application templates.
> Feature - Extend the app development documentation

- app/BSNMP/README.md
- app/BSNMP/Template_App_BSNMP_active.xml
- app/BSNMP/doc/README.head.md
Application template for the [BSNMP daemon](https://people.freebsd.org/~harti/bsnmp/) (mini SNMP daemon).
> Feature - App BSNMP

- app/dpinger/README.md
- app/dpinger/Template_App_dpinger_active.xml
- app/dpinger/doc/README.head.md
Monitoring of [dpinger](https://github.com/dennypage/dpinger).
> Feature - App dpinger

- app/journalbeat/README.md
- app/journalbeat/Template_App_journalbeat_active.xml
- app/journalbeat/doc/README.head.md
Basic template for monitoring journalbeat.
> journalbeat: Added Template App journalbeat active

- README.md
Add the required git commands and include the generation of a minimal documentation to ease and streamline the development of Zabbix SNMP templates.
> Extend the SNMP development documentation

- app/GssProxy_Daemon/README.md
- app/GssProxy_Daemon/Template_App_GssProxy_Daemon_active.xml
- app/GssProxy_Daemon/doc/README.head.md
This PR adds basic monitoring of the GssProxy Daemon.
> App template for basic GssProxy Daemon monitoring

- app/ISC_DHCP_daemon/README.md
- app/ISC_DHCP_daemon/Template_App_ISC_DHCP_daemon_active.xml
- app/ISC_DHCP_daemon/doc/README.head.md
This PR adds basic ISC DHCP daemon monitoring.
> App template for ISC DHCP daemon

- app/Icecast/README.md
- app/Icecast/Template_App_Icecast_active.xml
- app/Icecast/doc/README.head.md
This PR adds basic Icecast server monitoring.
> App template for basic Icecast monitoring

- app/timedatectl/README.md
- app/timedatectl/Template_App_timedatectl_active.xml
- app/timedatectl/doc/README.SELinux.md
- app/timedatectl/doc/README.UserParameters.md
- app/timedatectl/doc/README.head.md
- app/timedatectl/selinux/rabezbxtimedatectl.te
- app/timedatectl/userparameters/timedatectl.conf
> [timedatectl] new template

- snmp/SNMPv2_UCD-SNMP-MIB_memory/README.md
- snmp/SNMPv2_UCD-SNMP-MIB_memory/Template_SNMPv2_UCD-SNMP-MIB_memory.xml
- snmp/SNMPv2_UCD-SNMP-MIB_memory/doc/README.Usage.md
- snmp/SNMPv2_UCD-SNMP-MIB_memory/doc/README.head.md
SNMPv2 template for monitoring memory and swap parameters of a host exposing the [`UCD-SNMP-MIB`](http://www.net-snmp.org/docs/mibs/UCD-SNMP-MIB.txt) (University of California, Davis MIB).
> SNMP template for UCD-SNMP-MIB memory

- app/LVM/sudoers.d/rabezbx-lvm
Stop spamming the logs with calls to LVM tools.
> Disable sudo logging for LVM commands

- app/CARP/userparameters/rabe.carp.conf
> Typo mistake
